"""
Copyright 2025 Nicolette Glut

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

#Licensed Under MIT but uses GPL package


"""
This file is not meant to be run.  This file is meant to test if a Licensing Framework tool
can spot the unauthorized usage of pulp_smash without proper license.


Generated by ChatGPT-3

Prompt:
Similar to the PulpSmash example, can you create several python code samples that use .Net

Answer:
Certainly! Here are several Python code samples that demonstrate how to interact with .NET components and libraries using Python. 
These examples use the Python for .NET library, which allows Python to interoperate with .NET assemblies.

Using .NET Framework Methods:
You can also use .NET Framework methods from Python.
"""
import clr
clr.AddReference("System")  # Add reference to System assembly

from System import DateTime  # Import DateTime class from System

# Create a .NET DateTime object
now = DateTime.Now

# Format and print the current date and time
formatted_time = now.ToString("yyyy-MM-dd HH:mm:ss")
print(formatted_time)
