"""
This file is not meant to be run.  This file is meant to test if a Licensing Framework tool
can spot the unauthorized usage of pulp_smash without proper license.


Generated by ChatGPT-3

Prompt:
Similar to the PulpSmash example, can you create several python code samples that use .Net

Answer:
Certainly! Here are several Python code samples that demonstrate how to interact with .NET components and libraries using Python. 
These examples use the Python for .NET library, which allows Python to interoperate with .NET assemblies.

Using a .NET Class:
This example demonstrates how to use a .NET class from a .NET assembly in Python.
"""
import clr
clr.AddReference("System")  # Add reference to System assembly

from System.Collections import ArrayList  # Import ArrayList from System

# Create a .NET ArrayList
net_list = ArrayList()

# Add items to the list
net_list.Add("Item 1")
net_list.Add("Item 2")

# Access elements in the list
print(net_list[0])  # Output: Item 1
