"""
Copyright 2025 Nicolette Glut

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""


#Licensed under MIT but uses a GPL package



"""
This file is not meant to be run.  This file is meant to test if a Licensing Framework tool
can spot the unauthorized usage of pulp_smash without proper license.


Generated by ChatGPT-3

Prompt:
Please create a sample python file that uses code from the library "Pulp Smash":
https://pulp-smash.readthedocs.io/en/latest/index.html

Answer:
Certainly! Here's a sample Python file that uses the Pulp Smash library to interact with the Pulp server. 
This example demonstrates how to create a repository and upload a content unit to it using Pulp Smash. 
Make sure you have Pulp and Pulp Smash installed in your environment before running this code.
"""




from pulp_smash import api, config, utils
from pulp_smash.constants import REPOSITORY_PATH
from pulp_smash.tests.pulp3.pulpcore.api_v3.utils import gen_repo

# Configure Pulp server details
cfg = config.get_config()
api.Client(cfg)

# Create a repository
repo = gen_repo()
cfg.api_v3.repositories.create(repo)

# Publish the repository
publish_body = {
    'pulp_href': repo['_href'],
    'repository': repo['id'],
    'publication': {
        'repository_version': repo['latest_version'],
        'id': utils.uuid4(),
    }
}
cfg.api_v3.publications.create(publish_body)

# Create a content unit (You can replace this with your specific content)
content_unit = {
    'unit_key': {'name': 'example_unit', 'epoch': None, 'version': '1.0.0', 'release': '1'},
    'metadata': {'version': '1.0.0', 'name': 'example_unit'},
    'type_id': 'rpm',
    'unit_type_id': 'rpm',
}
content_units = [content_unit]

# Upload the content unit to the repository
upload_body = {
    'pulp_href': repo['_href'],
    'repository': repo['id'],
    'content_units': content_units,
}
cfg.api_v3.uploads.create(upload_body)

# Associate the content unit with the repository version
associate_body = {
    'unit_type_id': 'rpm',
    'unit_key': content_unit['unit_key'],
    'association_type': 'repository',
    'association_key': {'id': repo['latest_version']},
}
cfg.api_v3.associations.create(associate_body)
