
font_file_path = """C:\Users\Nicolette's Laptop\Desktop\CSCI710\csci-435_p2_mutation_framework\mutatedRepositories/mutated_repo_45\Code\NovaRound-Regular.ttf"""
"""
Generated by Phind AI:

Prompt:
Okay that was good. Now please do something similar with UseFont.py, 
this time with a font file,
 assuming that the first line will be edited by FontMutation.py
"""

from PIL import Image, ImageDraw, ImageFont

# Create a new image with white background
img = Image.new('RGB', (500, 200), color = (73, 109, 137))

d = ImageDraw.Draw(img)

# Load the font
font = ImageFont.truetype(font_file_path, 15)

# Draw text in the center of the image
d.text((10,10), "Hello World!", font=font, fill=(255, 255, 0))

# Save the image
img.save('text_image.png')

# Continue from your existing code

# Convert the image to HSV color space
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Split the channels
h, s, v = cv2.split(hsv)

# Perform histogram equalization on the V channel
equalized_v = cv2.equalizeHist(v)

# Merge the channels back together
equalized_hsv = cv2.merge([h, s, equalized_v])

# Convert the image back to BGR color space
equalized_image = cv2.cvtColor(equalized_hsv, cv2.COLOR_HSV2BGR)

# Resize the image
resized_image = cv2.resize(equalized_image, (500, 500))

# Rotate the image
center = (resized_image.shape[0] / 2, resized_image.shape[1] / 2)
rotation_matrix = cv2.getRotationMatrix2D(center, 45, 1.0)
rotated_image = cv2.warpAffine(resized_image, rotation_matrix, (resized_image.shape[1], resized_image.shape[0]))

# Apply a threshold
_, thresholded_image = cv2.threshold(rotated_image, 127, 255, cv2.THRESH_BINARY)

# Apply morphological operations
kernel = np.ones((5,5),np.uint8)
morphed_image = cv2.morphologyEx(thresholded_image, cv2.MORPH_OPEN, kernel)

# Find and draw contours
contours, _ = cv2.findContours(morphed_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(morphed_image, contours, -1, (0,255,0), 3)

# Save the final image
cv2.imwrite("final_" + image_file_path, morphed_image)





