"""
This file is not meant to be run.  This file is meant to test if a Licensing Framework tool
can spot the unauthorized usage of pulp_smash without proper license.


Generated by ChatGPT-3

Prompt:
Similar to the PulpSmash example, can you create several python code samples that use .Net

Answer:
Certainly! Here are several Python code samples that demonstrate how to interact with .NET components and libraries using Python. 
These examples use the Python for .NET library, which allows Python to interoperate with .NET assemblies.

Using .NET Framework Methods:
You can also use .NET Framework methods from Python.
"""
import clr
clr.AddReference("System")  # Add reference to System assembly

from System import DateTime  # Import DateTime class from System

# Create a .NET DateTime object
now = DateTime.Now

# Format and print the current date and time
formatted_time = now.ToString("yyyy-MM-dd HH:mm:ss")
print(formatted_time)
