
image_file_path = """C:\Users\Nicolette's Laptop\Desktop\CSCI710\csci-435_p2_mutation_framework\mutatedRepositories/mutated_repo_67\pantheon.jpg"""
"""
Generated by ChatGPT:

Prompt:
Make a python code that uses media such as a picture to do something without using the numpy project



Originally, this used a different AI and used numpy. However, the numpy project was licensed under GPL which automatically had a License conflict with MIT, which this project is under. Therefore, Licensing tools 
would flag this dependency.
"""
from PIL import Image

def convert_to_grayscale(image_path, output_path):
    # Open the image
    img = Image.open(image_path)
    
    # Convert the image to RGB (if it is not already in RGB)
    img = img.convert('RGB')
    
    # Create a new image object to store the grayscale image
    grayscale_img = Image.new('RGB', img.size)
    
    # Get the pixel data from the original image
    pixels = list(img.getdata())
    
    # Prepare a list to store the grayscale pixel data
    grayscale_pixels = []
    
    for pixel in pixels:
        r, g, b = pixel
        # Using the standard formula to calculate grayscale value
        grayscale_value = int(0.2989 * r + 0.5870 * g + 0.1140 * b)
        # Append the grayscale pixel (R, G, B) where all channels are the same
        grayscale_pixels.append((grayscale_value, grayscale_value, grayscale_value))
    
    # Put the grayscale pixels into the new image
    grayscale_img.putdata(grayscale_pixels)
    
    # Save the result
    grayscale_img.save(output_path)
    print(f"Grayscale image saved as {output_path}")

# Example usage
input_image = 'path_to_your_image.jpg'
output_image = 'output_grayscale_image.jpg'
convert_to_grayscale(input_image, output_image)
