
image_file_path = """C:\Users\Nicolette's Laptop\Desktop\CSCI710\csci-435_p2_mutation_framework\mutatedRepositories/mutated_repo_0\TestRepo2\Media\punisher.jpg"""
"""
Generated by Phind AI:

Prompt:
Right now, MediaMutation places a random media (img) file into a mutated repository.  
We would like to improve this by adding a code file that uses the inserted media.  
The idea is as follows. UseMedia file will be python file that does something (Doesn't matter what) using an image. 
The image to be used will be defined on line 1 of UseMedia.py.

In MediaMutation.py, MediaMutation will insert the media file, 
then will insert a copy of UseMedia.py into the same location, 
and then will edit the first line to use the inserted Media file.

What I need you to do is to generate the code for UseMedia.py.  
It needs to something with the image, though what it does specifically is up to you, 
so long as it is sufficiently long and unique.

Could I have a longer example, that does more stuff?
"""
from PIL import Image

def calculate_mean_color(image_path):
    # Open the image using PIL
    img = Image.open(image_path)
    
    # Convert the image to RGB (in case it's in another format like RGBA)
    img = img.convert('RGB')
    
    # Get the pixel data
    pixels = list(img.getdata())
    
    # Initialize variables to store the sum of RGB values
    total_r, total_g, total_b = 0, 0, 0
    
    # Loop through each pixel and sum the RGB values
    for pixel in pixels:
        r, g, b = pixel
        total_r += r
        total_g += g
        total_b += b
    
    # Calculate the mean RGB values
    num_pixels = len(pixels)
    mean_r = total_r / num_pixels
    mean_g = total_g / num_pixels
    mean_b = total_b / num_pixels
    
    return (mean_r, mean_g, mean_b)

# Example usage
image_path = 'path_to_your_image.jpg'
mean_color = calculate_mean_color(image_path)
print(f"The mean RGB color value is: {mean_color}")
