
image_file_path = """C:\Users\Nicolette's Laptop\Desktop\CSCI710\csci-435_p2_mutation_framework\mutatedRepositories/mutated_repo_0\TestRepo2\Media\punisher.jpg"""
"""
Generated by Phind AI:

Prompt:
Right now, MediaMutation places a random media (img) file into a mutated repository.  
We would like to improve this by adding a code file that uses the inserted media.  
The idea is as follows. UseMedia file will be python file that does something (Doesn't matter what) using an image. 
The image to be used will be defined on line 1 of UseMedia.py.

In MediaMutation.py, MediaMutation will insert the media file, 
then will insert a copy of UseMedia.py into the same location, 
and then will edit the first line to use the inserted Media file.

What I need you to do is to generate the code for UseMedia.py.  
It needs to something with the image, though what it does specifically is up to you, 
so long as it is sufficiently long and unique.

Could I have a longer example, that does more stuff?
"""

import cv2
import numpy as np

# Load the image
image = cv2.imread(image_file_path)

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply Gaussian blur
blur = cv2.GaussianBlur(gray, (5, 5), 0)

# Perform edge detection
edges = cv2.Canny(blur, 50, 150)

# Perform a dilation and erosion to close gaps in between object edges
dilated_edges = cv2.dilate(edges, None, iterations=2)
eroded_edges = cv2.erode(dilated_edges, None, iterations=1)

# Find contours in the eroded image, keep only the largest ones
contours, _ = cv2.findContours(eroded_edges.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]

# Initialize our canvas for drawing the output
output = image.copy()

# Loop over the contours
for contour in contours:
    # Approximate the contour
    peri = cv2.arcLength(contour, True)
    approx = cv2.approxPolyDP(contour, 0.02 * peri, True)

    # If our approximated contour has four points, then
    # we can assume that we have found our screen
    if len(approx) == 4:
        # Draw the contour on the image
        cv2.drawContours(output, [approx], -1, (0, 255, 0), 2)

# Save the output image
cv2.imwrite("output_" + image_file_path, output)